version: '3.3'
services:
  node:
    container_name: node
    build: ./node/
    ports:
      - "5000:5000"
    volumes:
      - ./node:/root/server

  nginx:
    build: ./nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
    #   - ./frontend/build:/var/www/html
      - ./nginx/default.conf:/etc/nginx/sites-available/default
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - node
